name: conformance
description: >-
  Conformance tests for connect

version: 0.3.0
homepage: https://connectrpc.com
documentation: https://connectrpc.com/docs
publish_to: none

executables:
  pipe:

environment:
  sdk: ^3.6.0
resolution: workspace
dependencies:
  protobuf: ">=4.0.0 <7.0.0"
  connectrpc:
    path: ../connect
  archive: ^3.6.1
  path: ^1.9.0
  args: ^2.5.0
  test: ^1.25.8
  stream_channel: ^2.1.2
  shelf: ^1.4.2
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1
dev_dependencies:
  tools:
    path: ../tools
